[ios_hq]
HQ-CSW1 ansible_host=172.17.254.1
HQ-CSW2 ansible_host=172.17.254.2

[ios_br]
BR-CSW1 ansible_host=172.18.254.1
BR-CSW2 ansible_host=172.18.254.2

[ios:children]
ios_hq
ios_br

[ios:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios

[asa_hq]
HQ-ASAs ansible_host=172.17.255.1

[asa_br]
BR-ASAs ansible_host=172.18.255.1

[asa:children]
asa_hq
asa_br

[asa:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.asa.asa

[hq:children]
ios_hq
asa_hq

[br:children]
ios_br
asa_br

[all_sites:children]
hq
br
